- "data/cost/cost_normalized.xlsx"
- "data/ecology/PP_cuboid_normalized.xlsx"
- "data/ecology/PP_impeller_normalized.xlsx"
- "data/ecology/PLA_cuboid_normalized.xlsx"
- "data/ecology/PLA_impeller_normalized.xlsx"
- "data/performance/performance_normalized.xlsx"
- "data/process/process_MFR_normalized.xlsx"
- "data/process/process_normalized.xlsx"